<form
	method="<?php echo $this->element->getMethod(); ?>"
	action="<?php echo $this->element->getAction(); ?>"
	id="<?php echo $this->element->getId('id'); ?>"
	class="<?php echo $this->element->getId('class'); ?>"
	enctype="<?php echo $this->element->getEncType(); ?>"
>
	<?php
		echo $this->{$this->element->control->helper}
				(
					$this->element->control->getName(),
					$this->element->control->getValue(),
					$this->element->control->getAttribs()
				);
	?>
	<li><p><?php echo $this->formLabel($this->element->email->getName(), $this->element->email->getLabel()) ?></p></li>
	<li>
		<div class="input1">
		<?php
			echo $this->{$this->element->email->helper}
					(
						$this->element->email->getName(),
						$this->element->email->getValue(),
						$this->element->email->getAttribs()
					);
		?>
		</div>	
		<?php if('<ul class="errors"><li></li></ul>' != ($this->element->email->getMessages())) { echo $this->formErrors($this->element->email->getMessages()); } ?>
		<small class="description"><?php echo $this->element->email->getDescription(); ?></small>
	</li>
	<li class="pt7">
		<?php
			echo $this->{$this->element->submit->helper}
					(
						$this->element->submit->getName(),
						$this->element->submit->getLabel(),
						$this->element->submit->getAttribs()
					);
		?>
	</li>
</form>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function(){
	$("#<?php echo $this->element->getId();?>").validationEngine();
});
<?php $this->headScript()->captureEnd() ?>