<h3>Galerie adaugata de <?php echo $this->gallery->getUser_Id()?TS_Catalog::userIdToModel($this->gallery->getUser_Id())->getUsername():"admin"?></h3>
<div class="empty10"></div>
<?php
$comments = TS_Catalog::galleryComments($this->gallery->getId());
if($comments){
	$commentsNr = count($comments);
?>
	<table width="100%" cellspacing="0" cellpadding="0" border="0" class="tableListingsAll">
		<tr>
			<th align="left" colspan="2">Comments(<?php echo $commentsNr;?>)</th>
		</tr>
		<tr>
			<th>Name</th>
			<th>Date</th>
		</tr>
		<?php foreach($comments as $value){?>
		<tr>
			<td><?php echo $value->getName();?></td>
			<td><?php echo date('d M, Y H:i:s', $value->getAdded())?></td>
		</tr>
		<?php }?>
	</table>
	<div class="empty10"></div>
<?php }?>

<?php
$favorites = TS_Catalog::galleryFavorites($this->gallery->getId());
if($favorites){
	$favoritesNr = count($favorites);
?>
	<table width="100%" cellspacing="0" cellpadding="0" border="0" class="tableListingsAll">
		<tr>
			<th align="left" colspan="2">Favorites(<?php echo $favoritesNr;?>)</th>
		</tr>
		<tr>
			<th>Name</th>
			<th>Date</th>
		</tr>
		<?php foreach($favorites as $value){?>
		<tr>
			<td><?php echo TS_Catalog::userIdToModel($value->getUserId())->getUsername();?></td>
			<td><?php echo date('d M, Y H:i:s', $value->getCreated())?></td>
		</tr>
		<?php }?>
	</table>
	<div class="empty10"></div>
<?php }?>