<?php if(NULL != $this->result){?>
	<table width="100%" cellspacing="0" cellpadding="0" border="0" class="tableListingsAll">
		<colgroup>
			<col width="" />
			<col width="150" />
		</colgroup>
		<tr>
			<th>Name</th>
			<th>Actions</th>
		</tr>
		<?php foreach($this->result as $value){?>
		<tr>
			<td>
				<?php echo $value->getName();?>
			</td>
			<td align="center">
				<a href="/admin/catalog/tagsedit/id/<?php echo $value->getId();?>" title="Edit">Edit</a>
				|
				<a href="/admin/catalog/tagsdelete/id/<?php echo $value->getId();?>" title="Delete">Delete</a>
			</td>
		</tr>
		<?php }?>
	</table>
	<?php if($this->itemCountPerPage < $this->totalItemCount){?>
		<?php echo $this->result;?>
	<?php }?>
<?php }?>