<form id="frmCreateCommercial" method="post" action="">
	<textarea name="code" style="height: 15px;"></textarea><input type="submit" value="create" style="position: relative; top: -7px;" />
</form>
<?php if($this->commercial){?>
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="tableListingsAll">
	<tr>
		<th>Code</th>
		<th>Status</th>
		<th>Created</th>
		<th>Actions</th>
	</tr>
	<?php foreach($this->commercial as $value){?>
	<tr>
		<td><?php echo $value->getCode();?></td>
		<td><?php echo $value->getStatus()?"active":"inactive";?></td>
		<td><?php echo date("d M, Y H:i:s", $value->getCreated());?></td>
		<td>
            <a href="/admin/marketing/edit/id/<?php echo $value->getId() ?>" title="Edit">edit</a>
            |
            <a href="/admin/marketing/status/id/<?php echo $value->getId() ?>" title="Status">status</a>
            |
            <a href="/admin/marketing/delete/id/<?php echo $value->getId() ?>" title="Delete">delete</a>
        </td>
	</tr>
	<?php }?>
</table>
<?php }else{?>
	No commercial in database!
<?php }?>