<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class'); ?>" enctype="<?php echo $this->element->getEncType();?>">	
<?php
	echo $this->{$this->element->message->helper}
	(
		$this->element->message->getName(),
		$this->element->message->getValue(),
		$this->element->message->getAttribs()
	);
?>
<?php if('<ul class="errors"><li></li></ul>' != ($this->element->message->getMessages())) { echo $this->formErrors($this->element->message->getMessages());}?>
<?php
	echo $this->{$this->element->submit->helper}
	(
		$this->element->submit->getName(),
		$this->element->submit->getValue(),
		$this->element->submit->getAttribs()
	);
?>
</form>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function(){
	$("#<?php echo $this->element->getId();?>").validationEngine();
});
<?php $this->headScript()->captureEnd() ?>