<div class="header_user" >
	<h1>Istoric</h1>
</div>
<h5>Cele mai vizitate 5 galerii</h5>
<div class="cele_maivizitate">
	<?php if($this->userMost5visited) { ?>
		<?php foreach($this->userMost5visited as $key => $value) { ?>
			<?php $product = new J_Product(); ?>
			<?php $product->Product($key, array('category', 'image')); ?>
			<div class="modul_galerie">
				<a href="/account/product-details/id/<?php echo $product->getId(); ?>"><img src="<?php echo $product->getSmallImage(); ?>" /></a>
				<ul>
					<li><h1><a href="#"><?php echo $product->getName(); ?></a></h1></li>
					<li class="vizite"><?php echo $value; ?> vizializari</li>
					<li class="categorie">Din: <a href="/catalog/categories/id/<?php echo $product->getCategoryId(); ?>"><?php echo $product->getCategory(); ?></a></li>
				</ul>
			</div>
		<?php } ?>
	<?php } ?>
	<div class="hr"></div>
	<div style="height:25px;">
		<h5 class="fl">Alte galerii</h5>
<!--		<div class=" sorteaza"><p>Sorteaza dupa:</p> <select name="" class="sortare"></select></div>-->
	</div>
	<?php if($this->result) { ?>
		<?php foreach($this->result as $value) { ?>
			<?php $product = new J_Product(); ?>
			<?php $product->Product($value->getId(), array('category', 'image', 'visits')); ?>
			<div class="modul_galerie">
				<a href="/account/product-details/id/<?php echo $value->getId(); ?>"><img src="<?php echo $product->getSmallImage(); ?>" /></a>
				<ul>
					<li><h1><a href="#"><?php echo $product->getName(); ?></a></h1></li>
					<li class="vizite"><?php echo $product->getVisits(); ?> vizializari</li>
					<li class="categorie">Din: <a href="/catalog/categories/id/<?php echo $product->getCategoryId(); ?>"><?php echo $product->getCategory(); ?></a></li>
				</ul>
			</div>
		<?php } ?>
	<?php } ?>
	<div class="hr"></div>
</div>