<?php if($this->result) : ?>
<?php $product = new J_Product(); ?>
<?php $tsStatistics = new TS_Statistics(); ?>
<?php $product->Product($this->result->getId(), array('category', 'images', 'comments', 'commentsNo')); ?>
<div class="modul_detaliu" >
<div class="header_galerie">
	<h1><?php echo $this->result->getName();?></h1>
	<p>
		<small>Postat in: <?php echo date('d F Y',$this->result->getAdded());?></small>
	</p>
</div>
	<div class="galerie">
		<?php 
		foreach($product->getBigImages() as $image) { ?>
			<img src="<?php echo $image; ?>" alt="<?php echo $this->result->getName();?>" title="<?php echo $this->result->getName();?>" />
		<?php } ?>
    </div>

	<div class="footer_galerie">
		<?php if(1 == 2){?>
		<div class="adaugat1">
			<?php $customer = $tsStatistics->getCustomerNameById($product->getUserId());?>
			<p>adaugat de:<br/><span><?php echo null != $customer?$customer:"admin";?></span></p>
		</div>
		<?php }?>
		<div class="social">
			<div class="google-plus-container fl">
				<div class="g-plusone" data-size="medium"></div>
				<script type="text/javascript">
				  window.___gcfg = {lang: 'ro'};

				  (function() {
					var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
					po.src = 'https://apis.google.com/js/plusone.js';
					var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
				  })();
				</script>
			</div>
			
			<div class="facebook-like-container fl">
				<div class="fb-like" data-href="<?php echo $this->facebookUrl;?>" data-send="false" data-layout="button_count" data-width="45" data-show-faces="false" data-font="arial"></div>
				<div id="fb-root"></div>
				<script>(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) {return;}
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=269917363026754";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>
			</div>
		</div>
		<div class="favorite">
		<a id="favorite"></a>
		<?php if(null == $this->loggedInUserId){?>
			<a href="/catalog/addtofavorites/id/<?php echo $product->getId();?>">
				<img src="/theme/default/images/favorite.gif" alt="adauga la favorite" title="Adauga la favorite" />
			</a>
		<?php }elseif(($product->getUserId() != $this->loggedInUserId) && ($tsStatistics->checkIfFavorited($this->loggedInUserId, $product->getId()) != true)){?>
			<a href="/catalog/addtofavorites/id/<?php echo $product->getId();?>">
				<img src="/theme/default/images/favorite.gif" alt="adauga la favorite" title="Adauga la favorite" />
			</a>
		<?php }else{?>
			<img src="/theme/default/images/adaugata.gif" alt="adaugat la favorite" title="Adaugat la favorite" />
		<?php }?>
		</div>
		<div class="raiting1">
						
			<script type="text/javascript" src="/theme/default/js/jquery-raty/jquery.raty.min.js"></script>
			<div class="fr">
				<div id="piti"></div>
<!--				<div id="hint"></div>-->
			</div>
			<script type="text/javascript">
			$(function(){
				$('#piti').raty({
					click: function(score, evt){
//						alert('ID: ' + this.attr('id') + '\nscore: ' + score + '\nevent: ' + evt);
						$.get('/ajax/statistics-rating/id/'+<?php echo $this->result->getId();?>+'/score/'+score, function(data) {
							if(data) {
								try {
									var items = eval('(' + data + ')');
								} catch (e) {}
								if(items) {
									
								}
							}
						});
					},
					path:'/theme/default/js/jquery-raty/img/',
					half: true,
					start: <?php echo $tsStatistics->calculateRating($this->result->getId());?>,
					target: '#hint',
					hintList: ['groaznic', 'slab', 'merge', 'misto', 'genial']
				});
			});
			</script>
			<p>Vizualizari: <?php echo $tsStatistics->calculateVisits($product->getId());?></p>
		</div>
		<div style="clear:both; height:1px;"></div>
		<?php if($this->result->getDescription()){ ?>
			<div class='descriptionGalery'>
				<?php echo $this->result->getDescription(); ?>
			</div>
		<?php } ?>	
	</div>

	<a id="comment"></a>
	<div class="empty10"></div>
	<?php if(!empty($this->message)){?>
		<?php foreach($this->message as $value){?>
			<?php echo $value;?>
			<div class="empty10"></div>
		<?php }?>
	<?php }?>

	<!--inceput comentarii-->
	<div class="comentarii">
		<div class="lasa_coment">
			<?php echo $this->form; ?>
		</div>

		<?php if($product->getCommentsNo() > 0){?>
		<div class="header_comentarii">
			<p><?php if($product->getCommentsNo() == '1') { echo $product->getCommentsNo().' comentariu'; } else { echo $product->getCommentsNo().' comentarii'; } ?></p>
		</div>
		<?php }?>
		<?php if($product->getComments()){
			foreach($product->getComments() as $value){
				$customer = $tsStatistics->customerModelById($value['userId'], array('id'=>'id', 'username'=>'username', 'avatar'=>'avatar'));
			?>
			<div class="modul_comentariu">
				<div class="left_comentariu">
					<?php if(null != $customer->getAvatar()){?>
						<img width="44" height="44" src="/media/avatar/small/<?php echo $customer->getAvatar();?>" alt="user" />
					<?php }else{?>
						<img width="44" height="44" src="/theme/default/images/user.gif" alt="user" />
					<?php }?>
				</div>
				<div class="right_comentariu">
					<p class="nume"><a href="#"><?php echo $value['name'];?></a> l <span><?php echo date('d/m/Y H:i', $value['added']); ?></span></p>
					<p class="descriere"><?php echo $value['comment']; ?></p>
				</div>
				<div style="clear:both; width:1px"></div>
			</div>
		<?php }} ?>
	</div>
</div>
<?php endif; ?>