<div class="header_user">
	<h1>Termeni si conditii de utilizare </h1>
</div>

<div class="text">
	<p>Utilizând şi/sau vizitând acest website (inclusiv tot conţinutul disponibil prin acest site) acceptati automat termenii si conditiile de utilizare a siteului.</p>
	<p>Acest Site este guvernat de niste Termeni pe care noi ii putem schimba oricand fara a fi obligati sa va anuntam. Ca atare, activitatea dumneavoastra pe acest Site va fi guvernata de acesti Termeni.</p>
	
	<h1>1. Inregistrarea</h1>
	<p>Aveti dreptul de a folosi Site-ul doar pentru a viziona content reprezentat de imagini. Ne rezervam dreptul de a va nega sau interzice accesul la Site sau la anumite zone ale Site-ului.</p>
	
	<h1>2. Limitarea accesului pe Site</h1>
	<p>Putem insa sa va blocam si accesul la Site. Ne rezervam dreptul de a modifica sau intrerupe temporar accesul la Site, iar dumneavoastra veti fi de acord ca nu suntem raspunzatori in fata dumneavoastra sau in fata unei terte parti pentru orice modificare sau suspendare a activitatii site-ului.</p>
	<p>Orice alte drepturi pe care nu vi le garantam dumneavoastra sunt detinute de noi. Nicio zona a acestui Site nu este rezervata copiilor. Fara permisiunea noastra scrisa nu puteti copia sau reproduce contentul de pe Site pe alte site-uri, de profil sau nu. Fara alte restrictii impuse, sunteti de acord ca nu veti copia, transmite, vinde, sau exploata in alt mod Site-ul cu scop comercial. Retineti ca pentru accesarea zonelor de content, ce exista sau vor fi dezvoltate pe Site, trebuie sa aveti 18 ani.</p>
	
	<h1>3. Limitari de responsabilitate</h1>
	<p>Ca administratori ai Site-ului, vom face toate eforturile rezonabile pentru a asigura acuratetea si increderea in site-ul nostru si va incerca sa corecteze erorile si omisiunile cat mai repede posibil. Cu toate acestea nu suntem responsabili pentru inadvertente, erori sau omisiuni in cadrul informatiilor furnizate de utilizatori.</p>
	<p>In mod expres, utilizatorul este de acord ca nu va fi responsabilitatea noastra pentru nici un fel de daune directe, indirecte, minore, speciale, de importanta majora sau incidentale, incluzand dar fara a se limita insa la pierderi de profit, vad comercial sau alte pierderi intangibile, rezultate din utilizarea serviciului sau orice alt aspect relationat serviciului.</p>
	<p>Utilizatorul este de acord sa protejeze si sa asigure pe operatorii, directorii, angajatii, sucursalele, filialele si reprezentantii sai de si impotriva oricaror cereri, pretentii, actiuni, impuneri, pierderi, daune, costuri (incluzand, fara nici un fel de limitare, onorariile avocatilor), cheltuieli, judecati, decizii, amenzi, regularizari sau alte obligatii rezultate sau relationate cu orice alta actiune a utilizatorului in legatura cu utilizarea serviciului sau orice alt aspect relationat serviciului.</p>
	
	<h1>4. Parola si securitatea pe Site</h1>
	<p>Sunteti responsabili pentru pastrarea confidentialitatii username-ului si parolei dumneavoastra si sunteti pe deplin raspunzatori de toate activitatile ce se desfasoara pe si de pe contul dumneavoastra.</p>
	<p>Sunteti de acord sa ne anuntati cat mai repede daca cineva foloseste contul dumneavoastra fara a avea autorizatie.</p>
	<p>Intelegeti si sunteti de acord ca noi putem folosi, pastra si distribui informatiile contului dumneavoastra daca ni se cere acest lucru in virtutea legilor existente in vigoare sau din proprie initiative, daca luam la cunostinta ca aceste informatii sau imagini sunt absolut esentiale pentru:<br />
	&bull; a servi ca proba intr-un proces;<br />
	&bull; a intari acesti Termeni si conditii;<br />
	&bull; a raspunde solicitarilor dumneavoastra de orice natura, sau pentru;<br />
	&bull; a proteja drepturile si/sau siguranta noastra, a userilor nostri si a publicului.</p>
	<p>Sunteti de acord ca procesul tehnic si transmiterea informatiei in momentul in care interactionati cu Site-ul, pot implica:<br />
	transmiterea prin diverse retele; si schimbari tehnice pentru cresterea adaptabilitatii la cerintele fiecarei retea in parte si a device-urilor.</p>
	
	<h1>5. Reguli de uz International</h1>
	<p>Cunoscand natura globala a Internetului, sunteti de acord sa respectati toate regulile locale referitoare la comportamentul in mediu online si imaginile acceptate. In special, sunteti de acord sa va supuneti tuturor legilor aplicabile in domeniul exportului de date (imagini) din tara in care aveti domiciliul catre Romania.</p>
	<h1>6. Garantii</h1>
	<p>Sunteti de acord sa aparati, sa garantati si sa nu aveti niciun fel de pretentii, explicite sau implicite, fata de Site, administratorii, ofiterii, directorii, angajatii si agentii sai. Sunteti de acord sa ii aparati si sa ii sustineti pe acestia ca fiind neraspunzatori in niciun fel fata de orice fel de pretentii, revendicari, reclamatii, daune, obligatii, pierderi, responsabilitati, costuri sau datorii, cereri (incluzand dar nelimitandu-se la onorariile avocatilor) provenite din:</p>
	<p>&bull; Utilizarea, vizitarea sau accesul dumneavoastra pe Site;<br />
	&bull; Incalcarea din partea dumneavoastra a oricaror termeni din acesti Termeni si conditii de utilizare;<br />
	&bull; Incalcarea de catre dumneavoastra a oricaror drepturi ale unei terte parti incluzand, fara insa a se limita la acestea, orice drept de proprietate intelectuala, drept de proprietate sau drept de confidentialitate; sau<br />
	&bull; Orice pretentie care ar proveni din cauzarea de daune unei terte parti ca urmare a vizionarii sau publicarii unui imagini postate de catre dumneavoastra pe Site. Aceasta obligatie de asigurare impotriva eventualelor pretentii fata de “sexypitipoanca.ro” si administratorii sai si de exceptare de la orice fel de penalitati si/sau daune solicitate de oricine, completeaza Termenii si conditiile de utilizare a Site-ului.</p>
	<h1>7. Politica de confidentialitate</h1>
	<p>Colectarea datalor dumneavostra personale, ne permite sa intelegem nevoile si cerintele dumneavostra, pentru a furniza content personalizat si pentru a adapta spatiul publicitar preferintelor dumneavoastra. Respectam confidentialitatea informatiilor preluate de la utilizatorii sai.</p>
	<p>&bull; Confidentialitate<br />
	Pentru a raspunde intrebarilor Dvs. si pentru a tine evidente despre folosirea site-ului nostru poate aparea necesitatea de a va cere informatii cu caracter personal, cum ar fi numele dumneavoastra, adresa, adresa de e-mail si numarul de telefon. Aceste informatii insa nu vor fi folosite pentru a va transmite alte oferte, informatii despre serviciile firmei noastre fara acordul dumneavoastra.<br />
	SexyPitipoanca.ro se obliga sa protejeze confidentialitatea vizitatorilor site-ului sau. Nici un fel de informatii cu caracter personal nu vor fi transmise catre terti, cu exceptia acelor terti parteneri SexyPitipoanca.ro care asigura buna functionare a acestui site.<br />
	Acest site poate utiliza tehnologii care ne permit colectarea anumitor informatii cu caracter tehnic despre dumneavostra: adresa dumneavoastra de internet, sistemul de operare folosit, tipul browser-ului, informatii despre traficul realizat de dumneavostra prin site-ul nostru. Toate aceste informatii colectate de SexyPitipoanca.ro prin intermediul site-ului au scopul de a ajuta la imbunatatirea serviciilor oferite de site, dar si a serviciilor SexyPitipoanca.ro.<br />
	&bull; Protejarea informatiilor confidentiale<br />
	Informatiile colectate de la dumneavostra sunt foarte importante si de aceea sunt confidentiale. Nu oferim informatiile coloctate unor terte persoane fara consimtamantul dumneavostra expres si prealabil. Totusi, putem furniza unor terti informatii de ordin general referitoare la vanzari, trafic in site precum si alte informatii, insa aceste statistici nu vor contine date cu caracter personal.<br />
	&bull; Nota de informare privind protectia datelor personale<br />
	Conform cerintelor Legii nr. 677/2001 pentru protectia persoanelor cu privire la prelucrarea datelor cu caracter personal si libera circulatie a acestor date, modificata si completata si ale Legii nr. 506/2004 privind prelucrarea datelor cu caracter personal si protectia vietii private in sectorul comunicatiilor electronice, va administra in conditii de siguranta si numai pentru scopurile specificate, datele personale pe care ni le furnizati despre dumneavoastra.<br />
	Va informam ca datele personale pe care ni le furnizati sunt prelucrate in scopul oferirii in conditii optime de catre serviciile pe internet si a serviciilor care tin de domeniul educatiei si culturii.<br />
	In momentul crearii contului aveti posibilitatea de a opta pentru primirea de informatii despre produsele, serviciile, evenimentele etc. oferite de serviciul nostru prin bifarea casutei corespunzatoare pe pagina de creare a contului.<br />
	Conform Legii nr. 677/2001, beneficiati de dreptul de acces, de interventie asupra datelor, dreptul de a nu fi supus unei decizii individuale si dreptul de a va adresa justitiei.<br />
	Totodata, aveti dreptul sa va opuneti prelucrarii datelor personale care va privesc si sa solicitati stergerea datelor. Sunteti de acord ca stergerea datelor personale ale dumneavoastra va fi urmata de stergerea contului dumneavoastra din sistem si de imposibilitatea de a accesa serviciul oferit.</p>
	<h1>8. Copyright</h1>
	<p>Nu conteaza daca Materialul contine sau nu o avertizare de copyright, pentru ca oricum este protejat de drepturi de autor.</p>
	<p>Cand observam sau suntem anuntati ca un Material, sau o parte a acestuia, existent la un moment dat pe Site-ul nostru incalca vreun drept de autor, il vom sterge definitiv, conform prevederilor legale in vigoare.</p>
	<p>Daca la un moment dat observati ca un anumit Material de pe Site va incalca drepturile de proprietate intelectuala, va rugam sa ne trimieti o notificare conform Termenilor si conditiilor de utilizare pentru ca noi sa putem proceda la stergerea Materialului in cauza.</p>
	<p>In cazul in care considerati ca un anume Material asupra caruia detineti drepturi de autor a fost eliminat de pe Site fara cunostinta sau acordul dumneavostra, va rugam sa ne contactati pentru a ne instiinta.</p>
	<h1>9. Incalcarea Termenilor si conditiilor</h1>
	<p>Va rugam sa raportati orice incalcare a acestor termini si conditii la <img style="position: relative;top: 3px;" src="/theme/default/images/email.gif" alt="email" title="contact" /></p>
</div>