<?php
if(Zend_Registry::isRegistered('currentUser'))
{
	$currentUser = $this->display_user;
	$userActivity = TS_SocialNetwork::userActivity($currentUser->getId(), 10);
?>
<?php if(Zend_Registry::isRegistered('authUser') && $currentUser->getId() == Zend_Registry::get('authUser')->getId()){?>
<div id="tabs" class="post">
	<ul class="post_tabs">
		<li class="tabs_stare">
			<a href="#tabs-1">Actualizeaza starea</a>
		</li>
		<li class="tabs_foto">
			<a href="#tabs-2">+ Adauga fotografie</a>	
		</li>
		<li class="tabs_video">
			<a href="#tabs-3">+ Adauga video</a>
		</li>
	</ul>
	<div id="tabs-1" class="modul">
		<div class="empty10"></div>
		<form name="frmNuffSaid" method="post" action="">
			<input type="hidden" name="action" value="status" />
			<textarea id="updateStatus" name="updateStatus" rows="" cols="" style='width: 500px;height: 24px;line-height: 24px;text-indent: 10px;border: 1px solid #ababab; color: #636363;' placeholder="La ce te gandesti"></textarea>
			<input style='width: 65px;height: 26px;position: relative;top: -4px;left: -4px;color: #000;font-weight: bold;font-size: 13px;border: 1px solid #ababab;border-left: none;' value='Trimite' type="submit" />
		</form>
	</div>
	<div id="tabs-2">
		<div class="empty10"></div>
		<form id="frmUploadGallery" method="post" action="">
			<input type="hidden" name="action" value="gallery" />
			<div class="photo_title">
				<input id="photo_title" name="photo_title" type="text" placeholder="Titlu galerie" value="" />
			</div>
			<div class="photo_categ">
				<?php $categs = TS_Catalog::getCategories();
				if($categs){
					$i =0 ;
					foreach($categs as $value){?>
					<input name="photo_categ" id="photo_categ_<?php echo $value->getId();?>" <?php if($i == 0){echo "checked='checked'";} ?> type="radio" value="<?php echo $value->getId();?>" />
					<label for="photo_categ_<?php echo $value->getId();?>"><?php echo $value->getName();?></label>
				<?php
					$i++;
					}
				} 
				?>
			</div>
			<div class="photo_description">
				<textarea id="photo_description" name="photo_description" placeholder="Descriere"></textarea>
			</div>
			<div class="photo_tags">
				<input id="photo_tags" name="photo_tags" type="text" placeholder="Adauga tag-uri separe prin virgula" value="">
			</div>
			<?php TS_Catalog::multipleUploaderJqueryUI('frmUploadGallery');?>
			<div class="empty10"></div>
			<input class="uplBtn photo_submit" type="submit" value="Trimite" />
		</form>
	</div>
	<div id="tabs-3">
		<div class="empty10"></div>
		<form id="frm_post_video" method="post" action="">
			<input type="hidden" name="action" value="video" />
			<div class="video_title">
				<input id="video_title" name="video_title" type="text" placeholder="Titlu clip" value="" />
			</div>
			<div class="video_url">
				<input id="video_url" name="video_url" type="text" placeholder="URL clip (youtube)" value="">
			</div>
			<div class="video_categ">
				<?php $categs = TS_Catalog::getCategories();
				if($categs){
					$i = 0;
					foreach($categs as $value){?>
					<input name="video_categ" id="video_categ_<?php echo $value->getId();?>" type="radio" <?php if($i==0){echo "checked='checked'";} ?> value="<?php echo $value->getId();?>" />
					<label for="video_categ_<?php echo $value->getId();?>"><?php echo $value->getName();?></label>
				<?php
					$i++;
					}
				} 
				?>
			</div>
			<div class="video_description">
				<textarea id="video_description" name="video_description" onfocus="if(this.value == 'Descriere. . . '){this.value = '';}" onblur="if(this.value == ''){this.value = 'Descriere. . . ';}">Descriere. . . </textarea>
			</div>
			<div class="video_tags">
				<input id="video_tags" name="video_tags" type="text" placeholder="Adauga tag-uri separe prin virgula" value="">
			</div>
			<input class="uplBtn video_submit" type="submit" value="Trimite" />
		</form>
	</div>
</div>
<?php } ?>
<?php if($userActivity){?>
	<?php foreach($userActivity as $value){?>
		<?php
		$product = new J_Product();
		$product->Product($value->getId(), array('category', 'image', 'commentsNo', 'description'));
		$zendView = new Zend_View;
		$link = $zendView->url(array('categoryName' => preg_replace('/\s+/','-', strtolower($product->getCategory())), 'productName' => preg_replace('/\s+/','-', strtolower($product->getName())), 'id' => $product->getId()), 'product');
		?>
		<div class="activity-item">
			<div class="activity_header">
				<div class="activity_avatar">
					<?php if(NULL != $currentUser->getAvatar()){?>
						<img width="80" src="/media/avatar/big/<?php echo $currentUser->getAvatar();?>" alt="<?php echo $currentUser->getUsername();?>" title="<?php echo $currentUser->getUsername();?>" />
					<?php }else{?>
						<img width="80" src="/theme/default/images/user.gif" alt="avatar" alt="<?php echo $currentUser->getUsername();?>" title="<?php echo $currentUser->getUsername();?>" />
					<?php }?>
				</div>
				<ul>
					<li>
						<p class="activity_username">
							<span><?php echo $currentUser->getUsername();?></span>
							I
							<em>in <?php echo date('d M, Y \l\a H:i:s', $value->getAdded());?></em>
						</p>
					</li>
					<li>
						<p class="activity_category">
							<?php if($value->getType() == 'status'){?>
								A scris pe perete: 
							<?php }else{?>
								A adaugat in categoria: <span><?php TS_SocialNetwork::categoryNameByCategoryId($value->getCategory_id())?></span>
								
								<?php if($value->getType() == 'gallery') {?>
								I <span class="activity_imagenr"><?php 
									$nrePoze = TS_SocialNetwork::countNumberOfPhotos($value->getid());
									echo $nrePoze;
									if($nrePoze == 1){
										echo ' poza';
									}else{
										echo ' poze';
									}
								} 
								?>
								</span>
							<?php }?>
						</p>	
					</li>
					<li>
						<h1 class="activity_name">
							<a href="<?php echo $link;?>"><?php echo $value->getName();?></a>
						</h1>
					</li>
				</ul>
				<div class="clear"></div>
			</div>
			<div class="activity_image">
				<?php
				if($value->getType() == 'gallery')
				{
					echo "<a href='".$link."' title='".$product->getName()."'>";
						if($product->getBigImage())
						{
							echo "<img width='533' src='".$product->getBigImage()."' alt='".$product->getName()."' title='".$product->getName()."' />";
						}
						else
						{
							echo "<img width='533' src='/theme/default/images/no-pic.jpg' alt='no image' title='no image found' />";
						}
					echo "</a>";
				}
				elseif($value->getType() == 'video')
				{
					$videoImage = TS_Products::getVideo($product->getId())->getImage();
					if(NULL != $videoImage)
					{
						echo "<a href='".$link."' title='".$product->getName()."'>";
							echo "<img width='533' src='/media/catalog/video/big/".$videoImage."' alt='".$product->getName()."' title='".$product->getName()."' />";
						echo "</a>";
					}
					else
					{
						echo "<a href='".$link."' title='".$product->getName()."'>";
							echo "<img width='533' src='/theme/default/images/no-video.jpg' alt='".$product->getName()."' title='".$product->getName()."' />";
						echo "</a>";
					}
				}
				elseif($value->getType() == 'embed')
				{
					echo "<a href='".$link."' title='".$product->getName()."'>";
						echo TS_ToHtml::videoThumb($product->getId());
					echo "</a>";
				}
				elseif($value->getType() == 'embed')
				{
					TS_ToHtml::videoPlayer($product->getId(), PLAYER_WIDTH, PLAYER_HEIGHT);
				}
				elseif($value->getType() == 'status')
				{
					; // nuff said
				}
				else
				{
					echo TS_Products::getVideo($value->getId())->getEmbed();
				}
				?>
				<?php if($value->getDescription()){?>
				<div class="activity-description">
					<p><?php echo nl2br($value->getDescription());?></p>
				</div>
				<?php }?>
				<div class="activity-actions">
					<?php if(Zend_Registry::isRegistered('authUser')){?>
					<div class="activity-actions-left">
						<ul>
							<?php if($currentUser->getId() != Zend_Registry::get('authUser')->getId()){?>
<!--							<li>-->
<!--								<a class="activity-action-like" href="#"></a>-->
<!--							</li>-->
							<li>
								<?php $isFavorited = TS_Catalog::checkIfFavorited(Zend_Registry::get('authUser')->getId(), $value->getId(), 'favorite');
								if($isFavorited){?>
									<a class="activity-action-adauga sel" href="javascript:;"></a>
								<?php }else{?>
									<span class='jsAddFav'>
										<a class="activity-action-adauga<?php if($isFavorited){echo " sel";}?>" rel="<?php echo $value->getId();?>" href="javascript:;"></a>
									</span>
									<script>
									$(document).ready(function(){
										$('.jsAddFav a').click(function(){
											var thisId = $(this).attr('rel');
											$.get('/ajax/addtofavorites/id/'+thisId+'/type/favorite', function(data) {
												if(data){
													$('.jsAddFav').html('<a class="activity-action-adauga sel" href="javascript:;"></a>');
												}
											});
										});
									});
									</script>
								<?php }?>
							</li>
<!--							<li>-->
<!--								<a class="activity-action-distribuie" href="#"></a>-->
<!--							</li>-->
							<li>
								<?php $isReported = TS_Catalog::checkIfFavorited(Zend_Registry::get('authUser')->getId(), $value->getId(), 'report');
								if($isReported){?>
									<a class="activity-action-denunta sel" href="javascript:;"></a>
								<?php }else{?>
									<span class='jsAddRep'>
										<a class="activity-action-denunta" rel="<?php echo $value->getId();?>" href="javascript:;"></a>
									</span>
									<script>
									$(document).ready(function(){
										$('.jsAddRep a').click(function(){
											var thisId = $(this).attr('rel');
											$.get('/ajax/addtofavorites/id/'+thisId+'/type/report', function(data) {
												if(data){
													$('.jsAddRep').html('<a class="activity-action-denunta sel" href="javascript:;"></a>');
												}
											});
										});
									});
									</script>
								<?php }?>
							</li>
							<?php }else{?>
<!--							<li>-->
<!--								<a class="activity-action-distribuie" href="#"></a>-->
<!--							</li>-->
							<?php }?>
						</ul>
					</div>
					<?php }?>
					<div class="activity-actions-right">
						<?php TS_ToHtml::socialShare($this->facebookUrl);?>
					</div>
				</div>				
				<div class="activity-comments">
					<div class="activity-comments-head"></div>
					<div class="activity-comments-content">
						<?php $firstComments = TS_Comments::getAllCommentsById($value->getId());?>
						<?php if(null != $firstComments){ ?>
							<div id="comentariuContainer">
							<?php foreach($firstComments as $comment){ ?>
								<?php $customer = TS_Statistics::customerModelById($comment->getUserId(), array('id'=>'id', 'username'=>'username', 'avatar'=>'avatar')); ?>
								
									<div class="modul_comentariu">
										<div class="left_comentariu2">
											<?php if($customer !== null && null != $customer->getAvatar()) { ?>
												<img width="44" height="44" src="/media/avatar/small/<?php echo $customer->getAvatar() ?>" alt="user" />
											<?php }else{ ?>
												<img width="44" height="44" src="/theme/default/images/user.gif" alt="user" />
											<?php } ?>							
										</div>
										<div class="right_comentariu2">
											<p class="nume">
												<a href="#"><?php echo $comment->getName() ?></a> l <span><?php echo date('d/m/Y H:i', $comment->getAdded()) ?></span>
											</p>
											<p class="descriere"><?php echo $comment->getComment(); ?></p>
											<div class="footer_comentariu2">
												<div class="left_footer_comentariu"></div>
											</div>
										</div>
										<div style="clear:both; width:1px"></div>
									</div>
							<?php } ?>
							</div>	
						<?php }else{?>
						<div id="comentariuContainer"></div>
						<?php }?>			
				</div>
				<?php if(Zend_Registry::isRegistered('authUser') && 0){?>
				<div class="activity-comments-action">
					<form class="formComentAdd" class="formComentAdd" action="" method="POST">						
						<input type="hidden" class="control" value="comentAdd" name="control">
						<input type="hidden" class="productId" value="<?php echo $value->getId();?>" name="product_id">
						<textarea class="txt validate[required]" class="messageComment" name="message"  maxlenght="1000"></textarea>
						<ul class="errors"><li></li></ul>	<small class="description"></small>
						<input type="submit" class="bt4" value="Trimite"  name="submit">
					</form>								
				</div>
				<?php }?>	
			</div>
			
			</div>
			
		</div>
	<?php }?>
	<script type="text/javascript">
//	$(document).ready(function() {
//		
//		//BEGIN:trimitere de comment normal
//		$('.formComentAdd').each(function(e) 	{
//			$(this).submit(function(e) 	{
//				e.preventDefault();
//			
//				var val = $(this).serialize();
//				$.post('/ajax/addcomment?'+val, function(data)
//				{
//					if(data)
//					{
//						try
//						{
//							var items = eval('(' + data + ')');
//						}
//						catch (e) {}
//						if(items)
//						{						
//							$('.messageComment').val('');
//							$('.jsCommentMessage').html(items['message']);
//							$('.comentariuContainer').prepend(items['comment']);					
//						}
//					}
//				});			
//			});
//			//END:trimitere de comment normal
//		});
//		
//
//	});
</script>
<?php }else{?>
Utilizatorul nu a postat nimic.
<?php
	}
}?>