<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>" id="<?php echo $this->element->getId('id'); ?>" class="<?php echo $this->element->getId('class'); ?>"	enctype="<?php echo $this->element->getEncType(); ?>">
    <table width="100%" cellpadding="0" cellspacing="0" border="0" class="tableAdmin box-tbl-info">
        <col width="200" />
        <col width="" />
        <tr>
            <th align="left" valign="middle">
                <?php
                $attribs = array();
                if ($this->element->title->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel(
                    $this->element->title->getName(),
                    $this->element->title->getLabel(),
                    $attribs
                );
                ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->title->helper}(
                    $this->element->title->getName(),
                    $this->element->title->getValue(),
                    $this->element->title->getAttribs()
                );
                ?>
                <?php if('<ul class="errors"><li></li></ul>'!=($this->element->title->getMessages())){ echo  $this->formErrors($this->element->title->getMessages());} ?>
                <div class="hint"><?php echo $this->element->title->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <td>
                <?php echo $this->{$this->element->submit->helper}(
                    $this->element->submit->getName(),
                    $this->element->submit->getValue(),
                    $this->element->submit->getAttribs()
                );
                ?>
            </td>
        </tr>
    </table>
</form>