<?php if(null != $this->result){?>
<form id="frmOptions" action="" method="post">
	<table width="100%" cellspacing="0" cellpadding="0" border="0" class="tableListingsAll">
		<colgroup>
			<col width="" />
			<col width="" />
		</colgroup>
		<tr>
			<th>Name</th>
			<th>Value</th>
		</tr>
		<?php foreach($this->result as $value){?>
		<tr>
			<td><?php echo $value->getName();?></td>
			<td><input type="text" name="option[<?php echo $value->getId();?>]" value="<?php echo $value->getValue();?>"></td>
		</tr>
		<?php }?>
	</table>
	<div class="empty10"></div>
	<input type="submit" value="Save Changes" />
</form>
<?php }else{?>
<div>No options were found in the database!</div>
<?php } ?>