<?php if($this->result){?>
<?php $product = new J_Product(); ?>
<?php $tsStatistics = new TS_Statistics(); ?>
<?php $product->Product($this->result->getId(), array('category', 'image', 'images', 'comments', 'commentsNo')); ?>
<div class="modul_detaliu" >
	<div class="header_galerie">
		<h1><?php echo $this->result->getName();?></h1>
		<p>
			<small><?php echo date('d F Y',$this->result->getAdded());?></small>
		</p>
	</div>
	
	<?php if($this->result->getType() == 'gallery'){?>
	<?php $img = TS_Statistics::firstImage($this->result->getId(),true); ?>
	<!-- Add the following three tags to your body -->
	<span itemprop="image" content="<?php echo $img; ?>"></span>
	
	<div class="galerie">
		<?php if($this->censored){ ?>
			<?php $img = TS_Statistics::firstImage($this->result->getId(),true); ?>
			<img src="<?php echo $img;?>" alt="<?php echo $this->result->getName();?>" title="<?php echo $this->result->getName();?>" />
			<div class="empty10">&nbsp</div>
			<div class="mess-false">Pentru a vizualiza restul galeriei trebuie sa va autentificati!</div>
			<div class="empty10">&nbsp;</div>
		<?php }else{ ?>			
			<?php if($product->getBigImage()){ ?>
				<?php
				foreach($product->getBigImages() as $image) { ?>
					<img src="<?php echo $image; ?>" alt="<?php echo $this->result->getName();?>" title="<?php echo $this->result->getName();?>" />
				<?php } ?>
			<?php }else {?>
				<img src="/theme/default/images/no-pic.jpg" alt="no image" title="no image found" />
			<?php } ?>
		<?php } ?>
    </div>
	<?php
	}elseif($this->result->getType() == 'embed'){
	?>
		<?php $img = TS_ToHtml::videoThumb($product->getId(),NULL,1); ?>
		<!-- Add the following three tags to your body -->
		<span itemprop="image" content="<?php echo $img; ?>"></span>
	<?php		
		TS_ToHtml::videoPlayer($product->getId(), PLAYER_WIDTH, PLAYER_HEIGHT);
	}else{
		?>
			<?php $img = TS_Statistics::firstImage($this->result->getId(),true); ?>
			<!-- Add the following three tags to your body -->
			<span itemprop="image" content="<?php echo $img; ?>"></span>
		<?php	
		echo TS_Products::getVideo($this->result->getId())->getEmbed();
	}
	?>

	<?php if($this->result->getDescription()){ ?>
	<div class='descriptionGalery'>
		<?php echo $this->result->getDescription(); ?>
	</div>
	<?php } ?>

	<div class="footer_galerie">		
		<?php TS_ToHtml::socialShare($this->facebookUrl);?>
		<?php if(Zend_Registry::isRegistered('authUser')){?>
		<div class="favorite activity-actions-left">
			<?php $isFavorited = TS_Catalog::checkIfFavorited(Zend_Registry::get('authUser')->getId(), $product->getId(), 'favorite');
			if($isFavorited){?>
				<a class="activity-action-adauga sel" href="javascript:;"></a>
			<?php }else{?>
				<span class='jsAddFav'>
					<a class="activity-action-adauga<?php if($isFavorited){echo " sel";}?>" rel="<?php echo $product->getId();?>" href="javascript:;"></a>
				</span>
				<script>
				$(document).ready(function(){
					$('.jsAddFav a').click(function(){
						var thisId = $(this).attr('rel');
						$.get('/ajax/addtofavorites/id/'+thisId+'/type/favorite', function(data) {
							if(data){
								$('.jsAddFav').html('<a class="activity-action-adauga sel" href="javascript:;"></a>');
							}
						});
					});
				});
				</script>
			<?php }?>
		</div>
		<?php }?>
		<div class="raiting1">
						
			<script type="text/javascript" src="/theme/default/js/jquery-raty/jquery.raty.min.js"></script>
			<div class="fr">
				<div id="piti"></div>
<!--				<div id="hint"></div>-->
			</div>
			<script type="text/javascript">
			$(function(){
				$('#piti').raty({
					click: function(score, evt){
						$.get('/ajax/statistics-rating/id/'+<?php echo $this->result->getId();?>+'/score/'+score, function(data) {
							if(data) {
								try {
									var items = eval('(' + data + ')');
								} catch (e) {}
								if(items) {
									
								}
							}
						});
					},
					path:'/theme/default/js/jquery-raty/img/',
					half: true,
					start: <?php echo $tsStatistics->calculateRating($this->result->getId());?>,
					target: '#hint',
					hintList: ['groaznic', 'slab', 'merge', 'misto', 'genial']
				});
			});
			</script>
			<p>Vizualizari: <?php echo $tsStatistics->calculateVisits($product->getId());?></p>
		</div>
		<div style="clear:both; height:1px;"></div>
	</div>

	<a id="comment"></a>
	<div class="empty10"></div>
	<?php if(!empty($this->message)){?>
		<?php foreach($this->message as $value){?>
			<?php echo $value;?>
			<div class="empty10"></div>
		<?php }?>
	<?php }?>

	<?php TS_ToHtml::similarGalleries($this->result->getId(), 4);?>

	
		<div class="comentarii">
			<div class="lasa_coment">
				
				<form class="formComentAdd" id="formComentAdd" action="" method="POST">
					<input type="hidden" id="control" value="comentAdd" name="control">
					<input type="hidden" id="productId" value="<?php echo $this->product_id; ?>" name="product_id">
					<div class="header_comentarii2">
						<p>Lasa un comentariu</p>
					</div>
					<div id="jsCommentMessage"></div>
					<?php if($this->account){ ?>
						<input name="nume" type="hidden" id="commentNume" value="<?php echo $this->account->getUsername(); ?>" />
						<input name="email" type="hidden" id="commentEmail" value="<?php echo $this->account->getEmail(); ?>"/>
					<?php } else{?>
						<input name="nume" onblur="if (this.value == '') {this.value = 'Nume';}" onfocus="if(this.value == 'Nume') {this.value = '';}" value="Nume" type="text" id="commentNume" class="txtInput validate[required]"  />
						<input name="email" onblur="if (this.value == '') {this.value = 'Email';}" onfocus="if(this.value == 'Email') {this.value = '';}" value="Email" type="text" id="commentEmail" class="txtInput1 validate[required]"  />
					<?php }?>
					
					<textarea class="txt validate[required]" id="messageComment" name="message"  maxlenght="1000"></textarea>
					<ul class="errors"><li></li></ul>	<small class="description"></small>
					<input type="submit" class="bt3" value="Trimite"  name="submit">
				</form>
				
				<div class="header_comentarii">
					<p>Comentarii (<?php echo $product->getCommentsNo();?>)</p>
				</div>
			</div>
			
			<?php $firstComments = TS_Comments::getAllCommentsById($this->result->getId());?>
			<?php if(null != $firstComments){ ?>
				<div id="comentariuContainer">
				<?php foreach($firstComments as $comment){ ?>
					<?php $customer = TS_Statistics::customerModelById($comment->getUserId(), array('id'=>'id', 'username'=>'username', 'avatar'=>'avatar')); ?>
					
						<div class="modul_comentariu">
							<div class="left_comentariu">
								<?php if($customer !== null && null != $customer->getAvatar()) { ?>
									<img width="44" height="44" src="/media/avatar/small/<?php echo $customer->getAvatar() ?>" alt="user" />
								<?php }else{ ?>
									<img width="44" height="44" src="/theme/default/images/user.gif" alt="user" />
								<?php } ?>							
							</div>
							<div class="right_comentariu">
								<p class="nume">
									<a href="#"><?php echo $comment->getName() ?></a> l <span><?php echo date('d/m/Y H:i', $comment->getAdded()) ?></span>
								</p>
								<p class="descriere"><?php echo $comment->getComment(); ?></p>
								<div id="all_raspunsCommentariu_<?php echo $comment->getId() ?>">
								<?php $childComment = TS_Comments::getChildComments($comment->getId()); ?>
									<?php if($childComment){ ?>
										<?php foreach ($childComment as $valueCC) { ?>
										<div class="raspunsCommentariu">
											<div class="left_comentariu_raspuns">
												<?php $customerRaspuns = TS_Statistics::customerModelById($valueCC->getUserId(), array('id'=>'id', 'username'=>'username', 'avatar'=>'avatar')); ?>
												<?php if($customerRaspuns !== null && null != $customerRaspuns->getAvatar()) { ?>
													<img width="44" height="44" src="/media/avatar/small/<?php echo $customerRaspuns->getAvatar() ?>" alt="user" />
												<?php }else{ ?>
													<img width="44" height="44" src="/theme/default/images/user.gif" alt="user" />
												<?php } ?>
											</div>
											<div class="right_comentariu_raspuns">
												<p class="nume">
													<a href="#"><?php echo $valueCC->getName() ?></a> l <span><?php echo date('d/m/Y H:i', $valueCC->getAdded()) ?></span>
												</p>
												<p class="descriere"><?php echo $valueCC->getComment(); ?></p>
											</div>
											<div class="clear"></div>
										</div>
										<?php } ?>							
								<?php } ?>
								</div>
								<div class="footer_comentariu">
									<div class="left_footer_comentariu">
		<!--								<ul>
											<li><a href="#">Imi place</a></li>
												<li>/</li>
												<li><a href="#">Distribuie</a></li>
										</ul>-->
									</div>
									<div class="right_footer_comentariu">
										<p>
											<a href="javascript: void(0)" rel="<?php echo $comment->getId(); ?>" class="showHideForm" id="showHideForm_<?php echo $comment->getId();  ?>">
												Raspunde
												<img src="/theme/default/images/default/sageata.png"/>
											</a>
										</p>

									</div>
								</div>
								<div class="modul_coment1 jsToggleComment-<?php echo $comment->getId(); ?>" id="jsToggleComment-<?php echo $comment->getId(); ?>" style="display: none">
									<div id="jsToggleCommentMessage-<?php echo $comment->getId(); ?>">
									</div>
									<form method="POST" action="" class="replyForm" rel="<?php echo $comment->getId(); ?>">
										<div>
											<input type="hidden" id="productId_<?php echo $comment->getId() ?>" value="<?php echo $this->product_id; ?>" name="product_id">
											<input type="hidden" id="parentId_<?php echo $comment->getId() ?>" value="<?php echo $comment->getId() ?>" name="parentId" class="f5"  />
											<?php if($this->account){ ?>
												<input name="userIdComment" type="hidden" id="userIdComment" value="<?php echo $this->account->getId(); ?>" />
												<input name="nume" type="hidden"  value="<?php echo $this->account->getUsername(); ?>" />
												<input name="email" type="hidden"  value="<?php echo $this->account->getEmail(); ?>"/>
											<?php }  else { ?>
												<input name="nume" id="nume_<?php echo $comment->getId() ?>" type="text"  class="f5 validate[required]" value="Nume" onfocus="if(this.value == 'Nume') {this.value = '';}"  onblur="if (this.value == '') {this.value = 'Nume';}" />
												<input name="email" id="email_<?php echo $comment->getId() ?>" type="text"  class="f5 ml20 validate[required]" value="Email" onfocus="if(this.value == 'Email') {this.value = '';}"  onblur="if (this.value == '') {this.value = 'Email';}" />
											<?php } ?>

										</div>
										<textarea name="message" cols="" rows="" id="message_<?php echo $comment->getId() ?>" class="txt" maxlenght="250" onfocus="if(this.value == 'Comentariu') {this.value = '';}"  onblur="if (this.value == '') {this.value = 'Comentariu';}">Comentariu</textarea>
										<input name="trimite" type="submit" value="Trimite" class="bt_trimite" />
									</form>
									<div class="clear"></div>
								</div>
							</div>
							<div style="clear:both; width:1px"></div>
						</div>
				<?php } ?>
				</div>	
			<?php }else{?>
			<div id="comentariuContainer"></div>
			<?php }?>			
		</div>	
</div>
<?php }?>

<script type="text/javascript">
	$(document).ready(function() {
		$("#formComentAdd").validationEngine();

		//BEGIN:trimitere de comment normal
		$('#formComentAdd').submit(function(e) 	{
			e.preventDefault();
		
			var val = $('#formComentAdd').serialize();
			$.post('/ajax/addcomment?'+val, function(data)
			{
				if(data)
				{
					try
					{
						var items = eval('(' + data + ')');
					}
					catch (e) {}
					if(items)
					{						
						$('#messageComment').val('');
						$('#jsCommentMessage').html(items['message']);
						$('#comentariuContainer').prepend(items['comment']);					
					}
				}
			});			
		});
		//END:trimitere de comment normal

		$(".showHideForm").each(function(){
			$(this).click(function(){
				var rel = $(this).attr('rel');
				$(this).toggleClass('selected');
				$(".jsToggleComment-"+rel).unbind().slideToggle(200);
			});
		});
		
		
		//
		//BEGIN:trimitere de comment Raspuns
		$(".replyForm").each(function(){		
			$(this).submit(function(e)
			{
				e.preventDefault();
				var val = $(this).serialize();
				$.post('/ajax/addcomment?'+val, function(data)
				{
					if(data)
					{
						try
						{
							var items = eval('(' + data + ')');
						}
						catch (e) {}
						if(items)
						{
							if (typeof items['parentId'] !== 'undefined' && items['parentId'] !== null)
							{
								if(items['success'] == 'true')
								{
									$('#all_raspunsCommentariu_'+items['parentId']).append(items['message']);
									$(".jsToggleComment-"+items['parentId']).hide("slow");
									$("#showHideForm_"+items['parentId']).removeClass('selected');
									$(this).remove
									$('#message_'+items['parentId']).val('');

								}
								else
								{
									$('#jsToggleCommentMessage-'+items['parentId']).html(items['message']);
								}
							}
						}
					}
				});				
			});
		});
		//END:trimitere de comment Raspuns

	});
</script>

