<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>" id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>" enctype="<?php echo $this->element->getEncType(); ?>">
	<?php echo $this->{$this->element->control->helper}($this->element->control->getName(), $this->element->control->getValue(), $this->element->control->getAttribs());?>
	<table width="385" align="center" cellpadding="0" cellspacing="0" border="0">
		<colgroup>
			<col width="165" />
			<col width="" />
		</colgroup>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->oldPassword->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->oldPassword->getName(), $this->element->oldPassword->getLabel(), $attribs);
					?>
				</p>
			</td>
			<td>
				<div class="input">
					<?php
						echo $this->{$this->element->oldPassword->helper}
								(
									$this->element->oldPassword->getName(),
									$this->element->oldPassword->getValue(),
									$this->element->oldPassword->getAttribs()
								);
					?>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->password->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->password->getName(), $this->element->password->getLabel(), $attribs);
					?>
				</p>
			</td>
			<td>
				<div class="input">
					<?php
						echo $this->{$this->element->password->helper}
								(
									$this->element->password->getName(),
									$this->element->password->getValue(),
									$this->element->password->getAttribs()
								);
					?>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->retypePassword->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->retypePassword->getName(), $this->element->retypePassword->getLabel(), $attribs);
					?>
				</p>
			</td>
			<td>
				<div class="input">
					<?php
						echo $this->{$this->element->retypePassword->helper}
								(
									$this->element->retypePassword->getName(),
									$this->element->retypePassword->getValue(),
									$this->element->retypePassword->getAttribs()
								);
					?>
				</div>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<?php
					echo $this->{$this->element->submit->helper}
							(
								$this->element->submit->getName(),
								$this->element->submit->getValue(),
								$this->element->submit->getAttribs()
							);
				?>
			</td>
		</tr>
	</table>
</form>	
</form>
<script type="text/javascript">
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();
	});
</script>