<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>" id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>" enctype="<?php echo $this->element->getEncType(); ?>">
	<?php echo $this->{$this->element->control->helper}($this->element->control->getName(), $this->element->control->getValue(), $this->element->control->getAttribs());?>
	<table width="400" cellpadding="0" cellspacing="0" border="0" align="center">
		<colgroup>
			<col width="160" />
		</colgroup>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->username->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->username->getName(), $this->element->username->getLabel(), $attribs);
					?>
					<span>*</span>
				</p>
			</td>
			<td>
				<div class="input1">
				<?php echo $this->{
				$this->element->username->helper}(
					$this->element->username->getName(),
					$this->element->username->getValue(),
					$this->element->username->getAttribs()
				);?>
				</div>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->username->getMessages())) { echo $this->formErrors($this->element->username->getMessages()); } ?>
				<small class="description"><?php echo $this->element->username->getDescription(); ?></small>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->passwordnew->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->passwordnew->getName(), $this->element->passwordnew->getLabel(), $attribs);
					?>
					<span>*</span>
				</p>
			</td>
			<td>
				<div class="input1">
				<?php
					echo $this->{$this->element->passwordnew->helper}
							(
								$this->element->passwordnew->getName(),
								$this->element->passwordnew->getValue(),
								$this->element->passwordnew->getAttribs()
							);
				?>
				</div>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->passwordnew->getMessages())) { echo $this->formErrors($this->element->passwordnew->getMessages()); } ?>
				<small class="description"><?php echo $this->element->passwordnew->getDescription(); ?></small>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->retypePassword->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->retypePassword->getName(), $this->element->retypePassword->getLabel(), $attribs);
					?>
					<span>*</span>
				</p>
			</td>
			<td>
				<div class="input1">
				<?php
					echo $this->{$this->element->retypePassword->helper}
							(
								$this->element->retypePassword->getName(),
								$this->element->retypePassword->getValue(),
								$this->element->retypePassword->getAttribs()
							);
				?>
				</div>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->retypePassword->getMessages())) { echo $this->formErrors($this->element->retypePassword->getMessages()); } ?>
				<small class="description"><?php echo $this->element->retypePassword->getDescription(); ?></small>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->email->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->email->getName(), $this->element->email->getLabel(), $attribs);
					?>
					<span>*</span>
				</p>
			</td>
			<td>
				<div class="input1">
				<?php echo $this->{
				$this->element->email->helper}(
					$this->element->email->getName(),
					$this->element->email->getValue(),
					$this->element->email->getAttribs()
				);?>
				</div>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->email->getMessages())) { echo $this->formErrors($this->element->email->getMessages()); } ?>
				<small class="description"><?php echo $this->element->email->getDescription(); ?></small>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->image->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->image->getName(), $this->element->image->getLabel(), $attribs);
					?>
					<span>*</span>
				</p>
			</td>
			<td>
				<div class="input">
					<?php
						echo $this->{$this->element->image->helper}
								(
									$this->element->image->getName(),
									$this->element->image->getValue(),
									$this->element->image->getAttribs()
								);
					?>
					<?php if('<ul class="errors"><li></li></ul>' != ($this->element->image->getMessages())) { echo $this->formErrors($this->element->image->getMessages()); } ?>
					<small class="description"><?php echo $this->element->image->getDescription(); ?></small>
				</div>
			</td>
		</tr>
		<tr>
			<td><p>Data nasteri <span>*</span></p></td>
			<td>
				<?php echo $this->{$this->element->birth_day->helper}(
					$this->element->birth_day->getName(),
					$this->element->birth_day->getValue(),
					$this->element->birth_day->getAttribs(),
					$this->element->birth_day->getMultioptions()
				);?>
				<?php echo $this->{
				$this->element->birth_month->helper}(
					$this->element->birth_month->getName(),
					$this->element->birth_month->getValue(),
					$this->element->birth_month->getAttribs(),
					$this->element->birth_month->getMultioptions()
				);
				?>
				<?php echo $this->{
				$this->element->birth_year->helper}(
					$this->element->birth_year->getName(),
					$this->element->birth_year->getValue(),
					$this->element->birth_year->getAttribs(),
					$this->element->birth_year->getMultioptions()
				);?>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					<?php
						$attribs = array(); if($this->element->gender->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->gender->getName(), $this->element->gender->getLabel(), $attribs);
					?>
				</p>
			</td>
			<td>
				<?php echo $this->{
				$this->element->gender->helper}(
					$this->element->gender->getName(),
					$this->element->gender->getValue(),
					$this->element->gender->getAttribs(),
					$this->element->gender->getMultioptions(),
					'&nbsp;&nbsp;&nbsp;'
				);?>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<?php echo $this->{$this->element->newsletter->helper}(
					$this->element->newsletter->getName(),
					$this->element->newsletter->getCheckedValue(),
					$this->element->newsletter->getAttribs()
				);?>
				<p>
					<?php
						$attribs = array(); if($this->element->newsletter->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->newsletter->getName(), $this->element->newsletter->getLabel(), $attribs);
					?>
				</p>
				<?php if(NULL != $this->element->newsletter->getMessages()){echo $this->formErrors($this->element->newsletter->getMessages());}?>
				<small class="description"><?php echo $this->element->newsletter->getDescription(); ?></small>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<?php echo $this->{$this->element->terms->helper}(
					$this->element->terms->getName(),
					$this->element->terms->getCheckedValue(),
					$this->element->terms->getAttribs()
				);?>
				<p>
					<?php
						$attribs = array(); if($this->element->terms->isRequired()) { $attribs['class'] = 'required'; }
						echo $this->formLabel($this->element->terms->getName(), $this->element->terms->getLabel(), $attribs);
					?>
					 <a target="_blank" href="/account/terms">termenii si conditiile</a>
				</p>
				<?php if(NULL != $this->element->terms->getMessages()){echo $this->formErrors($this->element->terms->getMessages());}?>
				<small class="description"><?php echo $this->element->terms->getDescription(); ?></small>
			</td>
		</tr>
		<tr>
			<td colspan="2" align="center">
				<?php echo $this->{
				$this->element->submit->helper}(
					$this->element->submit->getName(),
					$this->element->submit->getValue(),
					$this->element->submit->getAttribs()
				);?>
			</td>
		</tr>
	</table>
	<div class="footer_user">
		<p style="color: #797D92;">Toate campurile marcate cu <span style="font-weight: bold;">*</span> sunt obligatorii.</p>
	</div>
</form>
<script type="text/javascript">
$(function(){
	$('.selectmenu').selectmenu();
});
$(document).ready(function() {
	$("#<?php echo $this->element->getId();?>").validationEngine();
});
</script>