<?php if($this->items): ?>
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="tableListingsAll">
    <tr>
        <th>Url</th>
        <th>Actions</th>
    </tr>
    <?php foreach($this->items as $item): ?>
    <tr>
        <td><?php echo $item->getUrl() ?></td>
        <td><a href="/admin/import/import-element/id/<?php echo $item->getId() ?>">view elements</a></td>
    </tr>
    <?php endforeach ?>
</table>
<?php endif ?>