<a class="button1" href="/admin/import/add-source"><small>add source</small></a>
<div class="empty10"></div>

<?php if($this->sources){?>
    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="tableListingsAll">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Url</th>
            <th>Schema</th>
            <th>Created</th>
            <th>Actions</th>
        </tr>
        <?php foreach($this->sources as $value){?>
            <tr>
                <td><?php echo $value->getTitle() ?></td>
                <td><?php echo $value->getDescription() ?></td>
                <td><?php echo $value->getUrl() ?></td>
                <td><?php echo $value->getSchema() ?></td>
                <td><?php echo date("d M, Y H:i:s", $value->getCreated());?></td>
                <td>
                    <a href="/admin/import/import-item/id/<?php echo $value->getId() ?>" title="Items">items</a>
                    |
                    <a href="/admin/import/edit-source/id/<?php echo $value->getId() ?>" title="Edit">edit</a>
                    |
                    <a href="/admin/import/delete-source/id/<?php echo $value->getId() ?>" title="Delete">delete</a>
                </td>
            </tr>
        <?php }?>
    </table>
<?php }else{?>
    No sources in database!
<?php }?>