<?php echo $this->doctype(); ?>
<html>
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<style type="text/css">
html,body{
  margin:0;
  padding:0;
  height:100%;
  border:none
}
.box{
	border: 1px solid #dfdfdf;
}
</style>
</head>
<body>
	<table align="center" style="height: 100%; margin: 0px auto;">
		<tr>
			<td height="100%" valign="middle" align="center">
				<div class="box" style="margin: auto 0px;">
					<h2 style="text-align: center;">Ne cerem scuze dar site-ul se afla sub lucrari de intretinere!<br />Revenim in curand!</h2>
					<div style="text-align: center;"><img src="/images/alert.png" alt="in constructie" title="in constructie" /></div>
				</div>
			</td>
		</tr>
	</table>
</body>
</html>