<div class="log">
	<div class="tit">Autentificare</div>
	<?php echo $this->formAuth;?>
	<div class="mes">
		<?php if(!empty($this->message)){?>
			<?php foreach($this->message as $value){?>
				<?php echo $value;?>
			<?php }?>
		<?php }?>
	</div>
	<div class="clear"></div>
</div>

<script type="text/javascript">
$("a").click(function(e) {
    e.preventDefault();
    var link = $(this).attr("href");
    window.parent.location = link;
});
<?php if(NULL != $this->redirect){// Close Fancybox?>
	parent.$.fancybox.close();
<?php }?>

</script>